#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(1==1)
{

	while(SensorValue(lightSensor) < 40)
	{

		motor[motorA] = 15;
		motor[motorB] = 35;

	}
	while(SensorValue(lightSensor) >= 45)
	{
		motor[motorA] = 35;
		motor[motorB] = 15;

	}
	while(SensorValue(sonarSensor) < 80)
	{
	//turn left
	motor[motorA] = 50;
	motor[motorB] = 0;
	wait1Msec(2000);
	//forward
	motor[motorA] = 50;
	motor[motorB] = 50;
	wait1Msec(2000);
	//turn right
	motor[motorA] = 0;
	motor[motorB] = 50;
	wait1Msec(2000);
	//forward
	motor[motorA] = 50;
	motor[motorB] = 50;
	wait1Msec(4000);
	//turn right
	motor[motorA] = 0;
	motor[motorB] = 50;
	wait1Msec(2000);
	//forward
	motor[motorA] = 50;
	motor[motorB] = 50;
	wait1Msec(2000);
	//turn left
	motor[motorA] = 50;
	motor[motorB] = 0;
	wait1Msec(2000);
  }
}

}//end main
