#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(1==1) //while 1
{

  //Follwing line
  while(SensorValue(sonarSensor) > 30) //while 3
  {

		while(SensorValue(lightSensor) < 40)
		{
			motor[motorA] = 15;
			motor[motorB] = 35;
		}//End while

		while(SensorValue(lightSensor) >= 45)
		{
			motor[motorA] = 35;
			motor[motorB] = 15;
		}//End while

	}//End while 3

		while(SensorValue(sonarSensor) < 30) //while 2
	{
		motor[motorA] = 0;
		motor[motorB] = 0;
		wait1Msec(5000);

	}//End while 2


}//End while 1

}//end main
