#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const tSensors lightSensor = (tSensors) S3;
task main()
{

while(SensorValue(lightSensor) > 40)
{
	motor[motorA] = 50;
	motor[motorB] = 50;

}

motor[motorA] = -50;
motor[motorB] = -50;
wait1Msec(1000);

}
